language: minimal

branches:
  only:
    - master

services:
  - docker

script:
  - export COMPILER_VERSION=$(cat ./VERSION)
  - echo ${COMPILER_VERSION}
  - docker build --tag elnebuloso/google-closure-compiler --pull --rm --no-cache --build-arg VERSION=${COMPILER_VERSION} --file Dockerfile .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag elnebuloso/google-closure-compiler elnebuloso/google-closure-compiler:${COMPILER_VERSION}
  - docker push elnebuloso/google-closure-compiler:${COMPILER_VERSION}
  - docker push elnebuloso/google-closure-compiler