name: Release

on:
  push:
    branches:
      - master
    paths-ignore:
      - "CHANGELOG.md"
      - "README.md"

jobs:
  main:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Configuration
        run: |
          echo "::set-env name=TAG::elnebuloso/google-closure-compiler"
      - name: Version
        run: |
          export COMPILER_VERSION=$(cat ./VERSION)
          echo "::set-env name=COMPILER_VERSION::$COMPILER_VERSION"
      - name: Build
        run: |
          docker build --tag ${TAG} --pull --rm --no-cache --build-arg VERSION=${COMPILER_VERSION} --file Dockerfile .
      - name: Release
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag ${TAG} ${TAG}:${COMPILER_VERSION}
          docker push ${TAG}:${COMPILER_VERSION}
          docker push ${TAG}
